Repository HackSlashNITP/LibraLink, pull requests merged in 2023-11, with the labels that each got.

#14 Signup and SignIn Pages added with modification
  .gitignore
  lib/Screens/Auth/login_screen.dart
  lib/Screens/Auth/signup_screen.dart
Labels: good first issue

#16 Add books and notification page
  lib/Screens/Add_books.dart
  lib/Screens/notification.dart
  lib/books model/books.dart
  lib/main.dart
  lib/widgets/bookwidget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#15 HomePage added
  assets/images/Ellipse 6.png
  assets/images/Ellipse 7.png
  assets/images/Group 34.png
  assets/images/Group 37.png
  assets/images/Rectblack.png
  assets/images/Rectorange.png
  assets/images/Rectpurple.png
  assets/images/Vector (1).png
  assets/images/Vector 11.png
  assets/images/Vector.png
  assets/images/backgnd.png
  assets/images/bgimg.png
  assets/images/book.png
  assets/images/libdues.png
  assets/images/line.png
  assets/images/locateBook.png
  assets/images/nibuslib.png
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/home_screen.dart
  lib/main.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Labels: enhancement, good first issue
