Repository HackSlashNITP/LibraLink, pull requests merged in 2023-10, with the labels that each got.

#3 Issue related to broken link in readme file fixed
  README.md
Labels: documentation, good first issue

#8 Launcher icon updated
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  pubspec.lock
Labels: enhancement, good first issue

#12 Icon updated
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
Labels: good first issue

#13 Dues screen added
  .metadata
  assets/images/tick1.json
  ios/RunnerTests/RunnerTests.swift
  lib/duesScreen.dart
  lib/main.dart
  lib/noDuesScreen.dart
  macos/RunnerTests/RunnerTests.swift
  pubspec.lock
  pubspec.yaml
Labels: enhancement
